### ISSUE TITLE
Run time error: '1004' Cannot run the macro 'user_configure.mykeymap'. 

### ISSUE THREAD

**Issue by analyticd** [kjnh10/ExcelLikeVim#11]
rest of error message:

...the macro may not be available in this workbook or all macros may be disabled. "

The thing is, it works fine at first (since I have enabled macros and allowed trust center to do vba object access.)  But, once it happens, it just keeps happening. I am on Excel 2013. I can overcome it temporarily sometimes by going to Developer > Add-ins > and then reload vimx.xlam. I use English input method. Does it work consistently for you on Excel 2013?

**Comment by kjnh10** [comment]
Sorry for my late reply.

it's helpful if you tell me how to reproduce and screenshot.

Anyway, I started investigating the issue.

**Comment by kjnh10** [comment]
Maybe, this will be resolved if you make ~/vimx/user_configure.bas. (it may be empty file)

It's a custom file and not a must item. So I will fix this bug so that this won't happen when the file does not exist.

**Comment by kjnh10** [comment]
I fixed this bug in v2.3.4. Please download the latest version.

Thanks,

**Comment by analyticd** [comment]
Thank you kjnh10. I downloaded v2.3.4 and it does perform better. It causes a few issues here and there still but so far these remaining issues seem to be recoverable without restarting Excel and I can live with them for now. I haven't lived with the plugin long enough to be able to submit another report yet regarding them, but if I get time I will. 

The biggest issue remaining right now is to have undo. I see there is already an open issue for that, so I will comment there rather than here. Again thank you kjnh10 for your quick response to fix the issue I reported and release v2.3.4.
